source $HOME/.shell/defaults
source $HOME/.shell/myfunctions
source $HOME/.shell/myexports
source $HOME/.shell/myalias

VIRTUAL_ENV_DISABLE_PROMPT=true
function omg_prompt_callback() {
    if [ -n "${VIRTUAL_ENV}" ]; then
        echo "\e[0;31m(`basename ${VIRTUAL_ENV}`)\e[0m "
    fi
}
