# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions


[ -f ~/.fzf.bash ] && source ~/.fzf.bash

source /home/ratan/.oh-my-git/prompt.sh

alias gh-fork-sync='python3 /home/ratan/Desktop/Hacks-And-Scripts/git/sync-gh-forks.py'

VIRTUAL_ENV_DISABLE_PROMPT=true
function omg_prompt_callback() {
    if [ -n "${VIRTUAL_ENV}" ]; then
        echo "\e[0;31m(`basename ${VIRTUAL_ENV}`)\e[0m "
    fi
}
